
import React from 'react';

import { Inter } from 'next/font/google';
import './style.css';
import Nav from "@/app/components/nav"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'vehicleApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     <Nav/>
        {children}
        </body>
    </html>
  )
}
